name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test
        
      - name: Run Addition Test
        run: mvn test -Dgroups=test-add

      - name: Run Subtraction Test
        run: mvn test -Dgroups=test-subtract

      - name: Run Multiplication Test
        run: mvn test -Dgroups=test-multiply